name: CI

on:
    pull_request:
        branches: "*"

env:
    node_version: 20
    pnpm_version: 9

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v3
              with:
                  version: ${{ env.pnpm_version }}
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.node_version }}
                  cache: "pnpm"
            - name: Install dependencies
              run: pnpm install
            - name: Run check
              run: pnpm ci:check
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v3
              with:
                  version: ${{ env.pnpm_version }}
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ env.node_version }}
                  cache: "pnpm"
            - name: Install dependencies
              run: pnpm install
            - name: Build
              run: pnpm build
