name: CI

on:
    pull_request:

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v2
            - name: Install dependencies
              run: bun install
            - name: Run check
              run: bun run check
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v2
            - name: Install dependencies
              run: bun install
            - name: Run build
              run: bun run build
    test:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - uses: oven-sh/setup-bun@v2
          - name: Install dependencies
            run: bun install
          - name: Run tests
            run: bun run test
