name: CI

on:
    pull_request:

jobs:
    check:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            node-version: [22]
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v3
              with:
                  version: 10
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  cache: "pnpm"
            - name: Install dependencies
              run: pnpm install
            - name: Run check
              run: pnpm check
    build:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            node-version: [22]
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v3
              with:
                 version: 10
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  cache: "pnpm"
            - name: Install dependencies
              run: pnpm install
            - name: Build
              run: pnpm build
    test:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            node-version: [22]
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v3
              with:
                  version: 10
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  cache: "pnpm"
            - name: Install dependencies
              run: pnpm install
            - name: Test
              run: pnpm test
